name: CMake CI

on: [push, pull_request]

jobs:
  ci:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      - name: configure
        run: cmake .
      - name: build
        run: cmake --build .
      - name: test
        run: cmake --build . --target test
